/**
 * Generates supabase/seed.sql from the same data modules the app uses, so the
 * seeded backend and the demo catalogue never drift apart.
 *
 *   npx tsx scripts/generate-seed.ts
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { COUNTRIES } from "../lib/market/data/countries";
import { TAX_RATES } from "../lib/market/data/tax-rates";
import { LABOR_RATES } from "../lib/market/data/labor-rates";
import { TRANSPORT_RATES } from "../lib/market/data/transport-rates";
import { CATALOG } from "../data/catalog";
import { PRODUCT_MARKET_PRICES } from "../data/product-prices";

const q = (v: unknown) =>
  v === null || v === undefined
    ? "null"
    : typeof v === "number" || typeof v === "boolean"
      ? String(v)
      : `'${String(v).replace(/'/g, "''")}'`;

const lines: string[] = [
  "-- GENERATED by scripts/generate-seed.ts — do not edit by hand.",
  "-- Reference/market data + demo catalogue. Apply after 001_initial_schema.sql.",
  "begin;",
  "",
  "-- Countries -----------------------------------------------------------------",
];

for (const c of COUNTRIES) {
  lines.push(
    `insert into public.countries (code,name,currency_code,currency_symbol,locale,measurement_system,default_tax_rate,active) values (${[
      q(c.code), q(c.name), q(c.currencyCode), q(c.currencySymbol), q(c.locale), q(c.measurementSystem), c.defaultTaxRate, c.active,
    ].join(",")}) on conflict (code) do update set name=excluded.name, default_tax_rate=excluded.default_tax_rate;`,
  );
}

lines.push("", "-- Tax rates -----------------------------------------------------------------");
for (const t of TAX_RATES) {
  lines.push(
    `insert into public.tax_rates (country_code,name,rate,category,active) values (${[
      q(t.countryCode), q(t.name), t.rate, q(t.category), t.active,
    ].join(",")});`,
  );
}

lines.push("", "-- Labour rates ---------------------------------------------------------------");
for (const r of LABOR_RATES) {
  lines.push(
    `insert into public.labor_rates (country_code,category,unit,cost,currency_code) values (${[
      q(r.countryCode), q(r.category), q(r.unit), r.cost, q(r.currencyCode),
    ].join(",")});`,
  );
}

lines.push("", "-- Transport rates ---------------------------------------------------------");
for (const r of TRANSPORT_RATES) {
  lines.push(
    `insert into public.transport_rates (country_code,base_fee,per_km,per_m3,currency_code) values (${[
      q(r.countryCode), r.baseFee, r.perKm, r.perM3, q(r.currencyCode),
    ].join(",")});`,
  );
}

lines.push("", "-- Products ---------------------------------------------------------------");
for (const p of CATALOG) {
  lines.push(
    `insert into public.products (id,name,sku,brand,category,"group",subcategory,description,swatch,sprite,unit,color,style,surface,labor_category,waste_percent,demo) values (${[
      q(p.id), q(p.name), q(p.sku), q(p.brand), q(p.category), q(p.group), q(p.subcategory), q(p.description),
      q(p.swatch), q(p.sprite ?? null), q(p.unit), q(p.color), q(p.style), q(p.surface ?? null), q(p.laborCategory), p.wastePercent, p.demo,
    ].join(",")}) on conflict (id) do nothing;`,
  );
}

lines.push("", "-- Per-market product prices --------------------------------------------------");
for (const mp of PRODUCT_MARKET_PRICES) {
  lines.push(
    `insert into public.product_market_prices (product_id,country_code,price,currency_code,supplier,available,min_quantity,source) values (${[
      q(mp.productId), q(mp.countryCode), mp.price, q(mp.currencyCode), q(mp.supplier), mp.available, mp.minQuantity, q(mp.source),
    ].join(",")}) on conflict (product_id, country_code, supplier) do update set price=excluded.price, available=excluded.available;`,
  );
}

lines.push("", "commit;", "");

writeFileSync(resolve(import.meta.dirname, "../supabase/seed.sql"), lines.join("\n"));
console.log(`seed.sql written · ${COUNTRIES.length} countries, ${CATALOG.length} products, ${PRODUCT_MARKET_PRICES.length} prices`);
