/**
 * Generates supabase/seed.sql from the same data modules the app uses, so the
 * seeded backend and the demo catalogue never drift apart.
 *   npx tsx scripts/generate-seed.ts
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { COUNTRIES } from "../lib/market/data/countries";
import { STATES } from "../lib/market/data/states";
import { TAX_JURISDICTIONS, TAX_RATES } from "../lib/market/data/tax";
import { LABOR_RATES } from "../lib/market/data/labor-rates";
import { DELIVERY_RATES } from "../lib/market/data/delivery-rates";
import { CATALOG } from "../data/catalog";
import { PRODUCT_MARKET_PRICES } from "../data/product-prices";

const q = (v: unknown) =>
  v === null || v === undefined
    ? "null"
    : typeof v === "number" || typeof v === "boolean"
      ? String(v)
      : `'${String(v).replace(/'/g, "''")}'`;

const lines: string[] = [
  "-- GENERATED by scripts/generate-seed.ts — do not edit by hand.",
  "-- US reference/market data + demo catalogue. Apply after 001_initial_schema.sql.",
  "begin;",
  "",
  "-- Countries --------------------------------------------------------------",
];

for (const c of COUNTRIES) {
  lines.push(
    `insert into public.countries (code,name,currency_code,currency_symbol,locale,measurement_system,active) values (${[
      q(c.code), q(c.name), q(c.currencyCode), q(c.currencySymbol), q(c.locale), q(c.measurementSystem), c.active,
    ].join(",")}) on conflict (code) do update set name=excluded.name;`,
  );
}

lines.push("", "-- States ---------------------------------------------------------------");
for (const s of STATES) {
  lines.push(
    `insert into public.states (country_code,code,name,active) values (${[q("US"), q(s.code), q(s.name), s.active].join(",")}) on conflict (country_code,code) do nothing;`,
  );
}

lines.push("", "-- Tax jurisdictions + rates -------------------------------------------");
for (const j of TAX_JURISDICTIONS) {
  lines.push(
    `insert into public.tax_jurisdictions (id,country_code,state_code,county,city,zip_code,name,active) values (${[
      q(j.id), q("US"), q(j.stateCode), q(j.county), q(j.city), q(j.zipCode), q(j.name), j.active,
    ].join(",")}) on conflict (id) do nothing;`,
  );
}
for (const r of TAX_RATES) {
  lines.push(
    `insert into public.tax_rates (jurisdiction_id,rate,effective_from,effective_until,source,active) values (${[
      q(r.jurisdictionId), r.rate, q(r.effectiveFrom), q(r.effectiveUntil), q(r.source), r.active,
    ].join(",")});`,
  );
}

lines.push("", "-- Labor rates --------------------------------------------------------");
for (const r of LABOR_RATES) {
  lines.push(
    `insert into public.labor_rates (country_code,state_code,category,unit,cost,currency_code) values (${[
      q("US"), q(r.stateCode), q(r.category), q(r.unit), r.cost, q(r.currencyCode),
    ].join(",")});`,
  );
}

lines.push("", "-- Delivery rates ---------------------------------------------------");
for (const r of DELIVERY_RATES) {
  lines.push(
    `insert into public.delivery_rates (country_code,state_code,base_fee,per_mile,per_cu_yd,currency_code) values (${[
      q("US"), q(r.stateCode), r.baseFee, r.perMile, r.perCuYd, q(r.currencyCode),
    ].join(",")});`,
  );
}

lines.push("", "-- Products --------------------------------------------------------");
for (const p of CATALOG) {
  lines.push(
    `insert into public.products (id,name,sku,brand,category,"group",subcategory,description,swatch,sprite,unit,color,style,surface,labor_category,waste_percent,demo) values (${[
      q(p.id), q(p.name), q(p.sku), q(p.brand), q(p.category), q(p.group), q(p.subcategory), q(p.description),
      q(p.swatch), q(p.sprite ?? null), q(p.unit), q(p.color), q(p.style), q(p.surface ?? null), q(p.laborCategory), p.wastePercent, p.demo,
    ].join(",")}) on conflict (id) do nothing;`,
  );
}

lines.push("", "-- Per-state product prices (USD) -----------------------------------");
for (const mp of PRODUCT_MARKET_PRICES) {
  lines.push(
    `insert into public.product_market_prices (product_id,country_code,state_code,price,currency_code,supplier,available,min_quantity,lead_time_days,source) values (${[
      q(mp.productId), q("US"), q(mp.stateCode), mp.price, q(mp.currencyCode), q(mp.supplier), mp.available, mp.minQuantity, mp.leadTimeDays, q(mp.source),
    ].join(",")});`,
  );
}

lines.push("", "commit;", "");

writeFileSync(resolve(import.meta.dirname, "../supabase/seed.sql"), lines.join("\n"));
console.log(
  `seed.sql · ${STATES.length} states, ${TAX_JURISDICTIONS.length} tax jurisdictions, ${CATALOG.length} products, ${PRODUCT_MARKET_PRICES.length} prices`,
);
